In [1]:
# pip install spacy
# python -m spacy download en_core_web_sm # or en_core_web_lg for larger model
# pip3 install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz

# txt2onto2.0

In [2]:
import pandas as pd

In [3]:
best_preds = pd.read_csv("../results/7_children/best_predictions.csv")
metadata_cancer_document_processed = pd.read_csv("../demo/metadata_cancer_document_processed.tsv", sep='\t', names=['documents_processed'])

In [4]:
best_preds = best_preds.sort_values('ID_x')
best_preds.insert(loc=9, column='documents_processed', value=metadata_cancer_document_processed['documents_processed'].values)
best_preds

,ID_x,prob,log2(prob/prior),related_words,source,species,titles,summaries,documents,documents_processed,name,log2(auprc/prior),num_of_pos,pred_words,coef
497,GSE100075,0.360012,1.615781,"breast,cancer,cell,endocrine,estrogen,fulvestr...",MONDO_0003274,human,Discovery of naturally occurring ESR1 mutation...,We report the first discovery of naturally occ...,Discovery of naturally occurring ESR1 mutation...,discovery naturally occurring esr1 mutations a...,thoracic cancer,3.176188,308,"breast,lung,cancer,nsclc,esophageal,adenocarci...","12.385,8.911,5.896,3.287,2.918,2.403,2.350,2.3..."
643,GSE100327,0.145479,0.444369,"cancer,cell,expression,identify,lines,profiles",MONDO_0002516,human,RNA-sequencing profiles of five different panc...,E47 had been shown previously to inhibit cell ...,RNA-sequencing profiles of five different panc...,rnasequencing profiles five different pancreas...,digestive system cancer,2.944177,283,"colorectal,hcc,cancer,pancreatic,colon,carcino...","7.137,6.025,5.879,5.386,4.260,4.022,3.995,3.97..."
429,GSE100392,0.193274,2.045477,"adenocarcinoma,cancer,cells,lung,papillary,ptc...",MONDO_0021069,human,Altered gene expression by C1orf106 in papilla...,Chromosome 1 open reading frame 106 (C1orf106)...,Altered gene expression by C1orf106 in papilla...,altered gene expression c1orf106 papillary thy...,malignant endocrine neoplasm,4.059710,131,"hcc,hepatocellular,thyroid,carcinoma,hepg2,liv...","7.111,5.238,5.199,3.964,3.456,3.374,2.383,2.09..."
622,GSE100530,0.091240,0.707957,"malignancies,mutations,rna,splicing,types",MONDO_0000637,human,Mutational landscape of splicing genes and fun...,Hotspot mutations in the spliceosome component...,Mutational landscape of splicing genes and fun...,mutational landscape splicing genes functional...,musculoskeletal system cancer,3.700397,155,"aml,leukemia,myeloid,cml,acute,cebpa,k562,spli...","8.676,5.219,5.023,3.597,2.706,2.464,2.463,1.92..."
483,GSE100669,0.380585,1.695957,"biopsies,breast,cancer,cell,cells,clinical,cur...",MONDO_0003274,human,Immunophenotyping and Transcriptomic Outcomes ...,Cancer tissue functions as an ecosystem of a d...,Immunophenotyping and Transcriptomic Outcomes ...,immunophenotyping transcriptomic outcomes pdxd...,thoracic cancer,3.176188,308,"breast,lung,cancer,nsclc,esophageal,adenocarci...","12.385,8.911,5.896,3.287,2.918,2.403,2.350,2.3..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,GSE99596,0.869935,2.888645,"breast,cancer,cells,lung,survival",MONDO_0003274,human,SIRT7 Antagonizes TGF-Î² Signaling and Inhibit...,Protein deacetylase SIRT7 is significantly dow...,SIRT7 Antagonizes TGF-Î² Signaling and Inhibit...,sirt7 antagonizes tgf signaling inhibits breas...,thoracic cancer,3.176188,308,"breast,lung,cancer,nsclc,esophageal,adenocarci...","12.385,8.911,5.896,3.287,2.918,2.403,2.350,2.3..."
606,GSE99794,0.195522,0.870887,"cancer,cdkactivating,cell,cells,colon,expressi...",MONDO_0002516,human,Activation of the p53 transcriptional program ...,"Cdk7, the CDK-activating kinase and transcript...",Activation of the p53 transcriptional program ...,activation p53 transcriptional program sensiti...,digestive system cancer,2.944177,283,"colorectal,hcc,cancer,pancreatic,colon,carcino...","7.137,6.025,5.879,5.386,4.260,4.022,3.995,3.97..."
104,GSE99820,0.512934,3.512835,"androgen,cancer,castrationresistant,prostate,r...",MONDO_0002149,human,Effects of WCE herbal extract on hormone-refra...,Purpose: Androgen-deprivation therapy is the s...,Effects of WCE herbal extract on hormone-refra...,effects wce herbal extract hormonerefractory p...,reproductive system cancer,4.323934,126,"prostate,ovarian,cancer,cervical,serous,endome...","9.338,7.471,5.061,4.273,2.001,1.866,1.803,1.43..."
585,GSE99825,0.148781,1.045477,"cell,k562,knockdown,rnaseq,shrna,transcription...",MONDO_0000621,human,RNA-seq analysis of BORIS/CTCFL knockdown in K...,The study involved transcriptome analysis usin...,RNA-seq analysis of BORIS/CTCFL knockdown in K...,rnaseq analysis borisctcfl knockdown k562 cell...,immune system cancer,3.681880,197,"aml,leukemia,myeloma,myeloid,acute,mm,k562,cml...","7.759,6.240,6.077,4.037,3.342,3.101,3.000,2.58..."
267,GSE99857,0.303173,2.754203,"androgen,ar,cancer,castrationresistant,high,li...",MONDO_0002149,human,22Rv1 in vivo progression model,Purpose: Even in last stage of metastatic cast...,22Rv1 in vivo progression modelPurpose: Even i...,22rv1 vivo progression modelpurpose even last ...,reproductive system cancer,4.323934,126,"prostate,ovarian,cancer,cervical,serous,endome...","9.338,7.471,5.061,4.273,2.001,1.866,1.803,1.43..."

# lemmatization

In [5]:
import spacy
nlp = spacy.load("en_core_web_sm")
# import en_core_web_sm
# nlp = en_core_web_sm.load()

In [6]:
documents_processed_lemmatized = []
for index, row in best_preds.iterrows():
    text = nlp(row['documents_processed'])
    doc = ""
    
    for token in text:
        doc += f"{token.lemma_} "
        
    documents_processed_lemmatized.append(doc)

In [7]:
best_preds.insert(loc=10, column='documents_processed_lemmatized', value=documents_processed_lemmatized)

In [8]:
best_preds

,ID_x,prob,log2(prob/prior),related_words,source,species,titles,summaries,documents,documents_processed,documents_processed_lemmatized,name,log2(auprc/prior),num_of_pos,pred_words,coef
497,GSE100075,0.360012,1.615781,"breast,cancer,cell,endocrine,estrogen,fulvestr...",MONDO_0003274,human,Discovery of naturally occurring ESR1 mutation...,We report the first discovery of naturally occ...,Discovery of naturally occurring ESR1 mutation...,discovery naturally occurring esr1 mutations a...,discovery naturally occur esr1 mutation acquis...,thoracic cancer,3.176188,308,"breast,lung,cancer,nsclc,esophageal,adenocarci...","12.385,8.911,5.896,3.287,2.918,2.403,2.350,2.3..."
643,GSE100327,0.145479,0.444369,"cancer,cell,expression,identify,lines,profiles",MONDO_0002516,human,RNA-sequencing profiles of five different panc...,E47 had been shown previously to inhibit cell ...,RNA-sequencing profiles of five different panc...,rnasequencing profiles five different pancreas...,rnasequence profile five different pancreas ca...,digestive system cancer,2.944177,283,"colorectal,hcc,cancer,pancreatic,colon,carcino...","7.137,6.025,5.879,5.386,4.260,4.022,3.995,3.97..."
429,GSE100392,0.193274,2.045477,"adenocarcinoma,cancer,cells,lung,papillary,ptc...",MONDO_0021069,human,Altered gene expression by C1orf106 in papilla...,Chromosome 1 open reading frame 106 (C1orf106)...,Altered gene expression by C1orf106 in papilla...,altered gene expression c1orf106 papillary thy...,alter gene expression c1orf106 papillary thyro...,malignant endocrine neoplasm,4.059710,131,"hcc,hepatocellular,thyroid,carcinoma,hepg2,liv...","7.111,5.238,5.199,3.964,3.456,3.374,2.383,2.09..."
622,GSE100530,0.091240,0.707957,"malignancies,mutations,rna,splicing,types",MONDO_0000637,human,Mutational landscape of splicing genes and fun...,Hotspot mutations in the spliceosome component...,Mutational landscape of splicing genes and fun...,mutational landscape splicing genes functional...,mutational landscape splicing gene functional ...,musculoskeletal system cancer,3.700397,155,"aml,leukemia,myeloid,cml,acute,cebpa,k562,spli...","8.676,5.219,5.023,3.597,2.706,2.464,2.463,1.92..."
483,GSE100669,0.380585,1.695957,"biopsies,breast,cancer,cell,cells,clinical,cur...",MONDO_0003274,human,Immunophenotyping and Transcriptomic Outcomes ...,Cancer tissue functions as an ecosystem of a d...,Immunophenotyping and Transcriptomic Outcomes ...,immunophenotyping transcriptomic outcomes pdxd...,immunophenotype transcriptomic outcome pdxderi...,thoracic cancer,3.176188,308,"breast,lung,cancer,nsclc,esophageal,adenocarci...","12.385,8.911,5.896,3.287,2.918,2.403,2.350,2.3..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,GSE99596,0.869935,2.888645,"breast,cancer,cells,lung,survival",MONDO_0003274,human,SIRT7 Antagonizes TGF-Î² Signaling and Inhibit...,Protein deacetylase SIRT7 is significantly dow...,SIRT7 Antagonizes TGF-Î² Signaling and Inhibit...,sirt7 antagonizes tgf signaling inhibits breas...,sirt7 antagonize tgf signal inhibit breast can...,thoracic cancer,3.176188,308,"breast,lung,cancer,nsclc,esophageal,adenocarci...","12.385,8.911,5.896,3.287,2.918,2.403,2.350,2.3..."
606,GSE99794,0.195522,0.870887,"cancer,cdkactivating,cell,cells,colon,expressi...",MONDO_0002516,human,Activation of the p53 transcriptional program ...,"Cdk7, the CDK-activating kinase and transcript...",Activation of the p53 transcriptional program ...,activation p53 transcriptional program sensiti...,activation p53 transcriptional program sensiti...,digestive system cancer,2.944177,283,"colorectal,hcc,cancer,pancreatic,colon,carcino...","7.137,6.025,5.879,5.386,4.260,4.022,3.995,3.97..."
104,GSE99820,0.512934,3.512835,"androgen,cancer,castrationresistant,prostate,r...",MONDO_0002149,human,Effects of WCE herbal extract on hormone-refra...,Purpose: Androgen-deprivation therapy is the s...,Effects of WCE herbal extract on hormone-refra...,effects wce herbal extract hormonerefractory p...,effect wce herbal extract hormonerefractory pc...,reproductive system cancer,4.323934,126,"prostate,ovarian,cancer,cervical,serous,endome...","9.338,7.471,5.061,4.273,2.001,1.866,1.803,1.43..."
585,GSE99825,0.148781,1.045477,"cell,k562,knockdown,rnaseq,shrna,transcription...",MONDO_0000621,human,RNA-seq analysis of BORIS/CTCFL knockdown in K...,The study involved transcriptome analysis usin...,RNA-seq analysis of BORIS/CTCFL knockdown in K...,rnaseq analysis borisctcfl knockdown k562 cell...,rnaseq analysis borisctcfl knockdown k562 cell...,immune system cancer,3.681880,197,"aml,leukemia,myeloma,myeloid,acute,mm,k562,cml...","7.759,6.240,6.077,4.037,3.342,3.101,3.000,2.58..."
267,GSE99857,0.303173,2.754203,"androgen,ar,cancer,castrationresistant,high,li...",MONDO_0002149,human,22Rv1 in vivo progression model,Purpose: Even in last stage of metastatic cast...,22Rv1 in vivo progression modelPurpose: Even i...,22rv1 vivo progression modelpurpose even last ...,22rv1 vivo progression modelpurpose even last ...,reproductive system cancer,4.323934,126,"prostate,ovarian,cancer,cervical,serous,endome...","9.338,7.471,5.061,4.273,2.001,1.866,1.803,1.43..."

## BioSentVec

In [9]:
import sent2vec
from nltk import word_tokenize
from nltk.corpus import stopwords
from string import punctuation
from scipy.spatial import distance

In [10]:
model_path = "/work/pi_hrando_smith_edu/gold_standards/BioSentVec_PubMed_MIMICIII-bigram_d700.bin"
model = sent2vec.Sent2vecModel()

In [11]:
try:
    model.load_model(model_path)
except Exception as e:
    print(e)
print('model successfully loaded')

model successfully loaded

In [12]:
stop_words = set(stopwords.words('english'))
def preprocess_sentence(text):
    text = text.replace('/', ' / ')
    text = text.replace('.-', ' .- ')
    text = text.replace('.', ' . ')
    text = text.replace('\'', ' \' ')
    text = text.lower()

    tokens = [token for token in word_tokenize(text) if token not in punctuation and token not in stop_words]

    return ' '.join(tokens)

In [13]:
sentence = preprocess_sentence('Breast cancers with HER2 amplification have a higher risk of CNS metastasis and poorer prognosis.')
print(sentence)

breast cancers her2 amplification higher risk cns metastasis poorer prognosis

In [14]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /home/rfu_smith_edu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [15]:
sentence_vector = model.embed_sentence(sentence)
print(sentence_vector)

[[ 0.27253592  0.04016513 -0.13868049  0.06607066  0.03410426  0.03702081
   0.04780459  0.318374    0.1389506   0.14894584  0.03802885  0.16076139
   0.27367333  0.28947747 -0.3635127   0.1523829   0.00113982  0.15947492
  -0.00115095 -0.3911827   0.06040372 -0.30060792  0.5700456  -0.3073153
   0.05641874 -0.38538572  0.03242918 -0.01758919 -0.53824794 -0.2036874
   0.09088504  0.42208442  0.01777515  0.26457042  0.00444555 -0.4244185
   0.08552625 -0.01220523 -0.52954006 -0.19729511  0.3146897   0.39812556
  -0.73728865 -0.15572241  0.12493155 -0.189124    0.30150056 -0.13335498
  -0.22929646  0.1923776  -0.25276372  0.48184827 -0.11678692  0.074292
  -0.3565283   0.06902904 -0.16303737 -0.1516651  -0.16457589  0.2640424
  -0.2330729   0.03231101  0.3361209   0.35289383 -0.23463576 -0.29648
  -0.3083266   0.39252853 -0.24566592 -0.2444962   0.20645703 -0.04719147
   0.10580424  0.00649089 -0.2572806  -0.333023   -0.03018534 -0.042082
  -0.03446042  0.1267659   0.37817308 -0.38865507 -0.20552012 -0.34621498
  -0.1216602  -0.04652812 -0.02347284 -0.24400087  0.16549529 -0.06411781
   0.01422617 -0.12668294  0.5960534   0.02109158  0.16629732  0.17482263
  -0.12253477  0.12936321  0.15015826  0.09612935  0.03910794 -0.09146566
  -0.43439966 -0.07247142  0.26412925 -0.17527688 -0.13276757  0.20395164
  -0.05921361  0.16484062  0.18909335 -0.09065875  0.14640309 -0.04357425
  -0.31174526  0.13512115 -0.15826614  0.05530081 -0.32504323  0.20767705
  -0.0941015  -0.01312271 -0.10174442  0.03745251 -0.14577436 -0.11705701
   0.24673483 -0.29994592 -0.03089786  0.05221201  0.4669998   0.00442661
   0.26255304 -0.0520683   0.24765283 -0.28208813  0.02101091 -0.2309345
  -0.27185237 -0.06502334  0.04894404 -0.12051236  0.19054177  0.33650944
   0.21696663 -0.09382363  0.04122993  0.02740302 -0.1523489   0.06898607
   0.3646409   0.00145511  0.23472148  0.08020525 -0.06348559  0.38403732
  -0.19614884  0.05751961  0.25427777 -0.06352087 -0.00501605  0.12870164
  -0.12095109  0.01321181  0.30547306 -0.12648751 -0.22209032  0.20374553
   0.30825672 -0.2554286   0.08377017  0.29781944 -0.29899627 -0.07965458
  -0.18984668 -0.13143328  0.02504029 -0.15191814 -0.02388869 -0.06577343
  -0.3067318  -0.07350196  0.07532682  0.04892201 -0.01745802 -0.10110494
  -0.01072426 -0.01015269  0.232459   -0.32037356 -0.09599126 -0.09170408
   0.07457744  0.10797482 -0.16640112 -0.02322571 -0.22640668 -0.32701987
   0.29183394 -0.08617553  0.07842809  0.18027404  0.32083857 -0.29391503
  -0.37091807  0.1317559  -0.04133325  0.02105725  0.06929144 -0.45651826
   0.06086781  0.43626273  0.02961666  0.14899905  0.25753006 -0.15902318
   0.27228698 -0.012717   -0.3683212   0.3146828   0.00246162 -0.2528494
  -0.01773234 -0.16845916  0.15252198  0.05695811 -0.4019833   0.11004736
  -0.4061533  -0.01654322 -0.08055133 -0.06888298  0.03975208 -0.12505263
  -0.4766509  -0.1302982  -0.15458837  0.19499418 -0.20499982  0.01576013
  -0.04100087 -0.03823095  0.01355971  0.31886473  0.3207466   0.30761683
  -0.58859974 -0.05454841  0.09202857  0.07083365  0.12124014 -0.15489404
  -0.1249956   0.19807188  0.02977463  0.06490497  0.0862143   0.09217765
  -0.39212793 -0.1090506   0.3700054   0.2391053   0.1204542   0.06182214
  -0.20115142 -0.19802506 -0.12779813  0.18747202  0.0733431  -0.09663613
  -0.24403886  0.16471218 -0.12632118  0.3087525  -0.12539518 -0.02084013
  -0.07293235 -0.38778466 -0.20683263  0.06490733  0.05344631 -0.28166145
   0.0709516  -0.05099153  0.26141232 -0.02879013  0.3863618  -0.03771535
   0.04465518  0.25189495 -0.05824171  0.04616535 -0.33440518  0.05650642
   0.01963214  0.04899212 -0.12409336 -0.02178784 -0.02102915  0.02570555
   0.13620213  0.01591191 -0.51012826 -0.11808088  0.16109395 -0.12763613
  -0.09608371 -0.223153    0.10025517  0.110238    0.04289898  0.43777797
  -0.07757877  0.3245564  -0.0072146   0.36475793 -0.23756203 -0.14881566
   0.1897787  -0.22575381  0.32615083  0.16910845 -0.08788409 -0.07606266
  -0.03706334  0.08212929 -0.19536538  0.19984807  0.04603511 -0.26996538
   0.04950259 -0.03615545  0.1406415   0.2947527  -0.00611998 -0.05985891
   0.01984618 -0.03949784 -0.01525426  0.29419264 -0.01415043 -0.17652188
  -0.06262738 -0.22616321  0.25551927 -0.02472711  0.15726517 -0.14524549
  -0.11207764  0.10489892  0.14721154  0.1193269  -0.0470333   0.08068092
   0.06711143 -0.1101417   0.00740551  0.23555118 -0.04884436 -0.29348636
   0.36853147  0.09429416  0.22065276  0.23430087 -0.0068337   0.06033167
   0.14368132 -0.28589955  0.32065156 -0.02703334  0.14414166  0.11144061
  -0.09757377  0.08389441  0.4110573  -0.17193225 -0.17498371  0.12369279
  -0.17010431 -0.09807961 -0.07679521  0.13369125  0.13676417 -0.16726981
   0.39855367  0.0587613   0.12028298  0.01342451 -0.07659346  0.03576399
  -0.04420809  0.12297461  0.02851038 -0.01444774 -0.01379851 -0.08932398
   0.28293097 -0.1373159   0.16300136  0.12364378 -0.2913006   0.25817928
  -0.01344534 -0.24683551 -0.08785618 -0.1017781  -0.12594536 -0.17217784
   0.12956655 -0.13296415  0.22922768  0.15616998 -0.2765172  -0.3030905
   0.03086687 -0.00273167 -0.15588386 -0.05675261 -0.09152196  0.26230586
  -0.01163875 -0.2478254   0.260964   -0.05098752 -0.02663371  0.08234623
   0.34928283  0.8313451   0.02071937  0.24742903 -0.06239458  0.09169593
   0.00140471 -0.06047087 -0.35359547  0.12234055  0.18345007 -0.14262569
  -0.11202564  0.274945   -0.06307555  0.20897087  0.22961979 -0.31827667
   0.12434521  0.09456863 -0.132533   -0.13584521 -0.36066884 -0.05460902
  -0.14705043 -0.08507536  0.22685164  0.24383776  0.20274445  0.07966835
  -0.06932851 -0.01657332 -0.35544744 -0.22558543 -0.0651169   0.08119379
   0.3001279  -0.01761239 -0.01498686  0.11016284  0.2519153   0.02833793
  -0.28951043  0.06437117 -0.25671995 -0.03743215 -0.22699313  0.24525918
   0.04435244 -0.25781178  0.00997334 -0.07835439  0.22938563 -0.07016336
  -0.24928015 -0.18942201 -0.1236209  -0.44305456  0.53566355 -0.18446858
   0.30429277 -0.11268931 -0.11295509  0.25952902  0.19171143  0.07295282
  -0.01309466  0.15677398 -0.1115496  -0.11746953 -0.34486744  0.01961437
   0.08887484  0.1231166  -0.22707342  0.14050385  0.02042234 -0.27477872
  -0.32859874  0.15609217 -0.15527791 -0.03412036 -0.13152814  0.5236449
   0.19360445 -0.18125863  0.41408825  0.17874481 -0.0879835  -0.11195815
  -0.08948261  0.23711275  0.10845808 -0.22963704  0.02916685  0.04244966
  -0.0449315  -0.16313884 -0.36450905  0.06882233  0.10855233  0.3169161
  -0.33788228 -0.11677711 -0.36983833  0.09579375 -0.02219467  0.11477247
   0.02546611  0.08161401  0.08159067 -0.2501985  -0.23828559  0.36675447
  -0.15668799  0.20695254  0.27773544  0.47669446  0.01058489  0.27333802
  -0.39817995  0.23312205  0.11152606 -0.15429601 -0.21768859  0.02197697
  -0.05461999  0.11158564 -0.3009951   0.04721674  0.33778647 -0.22506985
   0.2090023   0.13018404 -0.17677754 -0.09073435 -0.157161   -0.12982582
  -0.13903137  0.01262058 -0.06162163  0.11507569  0.21850152  0.09291503
   0.13182876  0.02859347  0.12657352  0.3068309  -0.15490891 -0.04232102
   0.062854   -0.15683283 -0.2431332  -0.20136073 -0.32315066  0.05642203
  -0.16685694  0.24037287 -0.10076776 -0.15987408  0.04036417  0.06853651
   0.06721435  0.09657718  0.21487527  0.04389333 -0.42330703 -0.12825093
  -0.12326848 -0.26695827  0.0649719  -0.32621393 -0.09277593  0.04695158
   0.16902225  0.12192411  0.02212488 -0.13833636  0.21684082 -0.15384167
   0.00954215  0.21829392 -0.10491441  0.38043278 -0.08237162  0.22160071
   0.07220576  0.3385922   0.18430929 -0.01216795  0.20997563  0.04614374
   0.5460487  -0.02897776  0.14775318  0.31089064  0.27132967 -0.08209523
   0.23873891 -0.06413503 -0.07715333 -0.02231805 -0.00694238  0.37205717
  -0.1450972  -0.0704605  -0.02053621  0.11540693 -0.11201832 -0.1471214
   0.04950135 -0.04224805  0.21448477 -0.22363718  0.02988946  0.07961679
   0.02574715 -0.17271668  0.325553    0.01628166 -0.05568108 -0.3240605
  -0.1429462   0.05608758 -0.01153869  0.03438982  0.08489512 -0.03345412
  -0.04629951 -0.40246782  0.06087665  0.20731504 -0.20592833  0.2631903
   0.12083606  0.03901361  0.22229938 -0.2662993   0.20107882 -0.20194705
   0.12862273 -0.14036344 -0.23233241 -0.08034117  0.12506847 -0.1897902
   0.0618707   0.15091741 -0.4029728  -0.10979341 -0.10763265  0.235283
  -0.08089121  0.03753055  0.2415903  -0.33070192  0.03716518  0.33133337
  -0.13763449 -0.0574756   0.32341847  0.10362037  0.12447642 -0.19017035
   0.00549802  0.10385241  0.01570529 -0.11430962 -0.01734808 -0.10625661
  -0.1896727   0.0568063   0.04407496  0.16548488]]

In [16]:
print(sentence_vector.shape)

(1, 700)

In [17]:
sentence_vector1 = model.embed_sentence(preprocess_sentence('Breast cancers with HER2 amplification have a higher risk of CNS metastasis and poorer prognosis.'))
sentence_vector2 = model.embed_sentence(preprocess_sentence('Breast cancers with HER2 amplification are more aggressive, have a higher risk of CNS metastasis, and poorer prognosis.'))

cosine_sim = 1 - distance.cosine(sentence_vector1, sentence_vector2)
print('cosine similarity:', cosine_sim)

ValueError: Input vector should be 1-D.

In [ ]:
sentence_vector3 = model.embed_sentence(preprocess_sentence('Furthermore, increased CREB expression in breast tumors is associated with poor prognosis, shorter survival and higher risk of metastasis.'))
cosine_sim = 1 - distance.cosine(sentence_vector1, sentence_vector3)
print('cosine similarity:', cosine_sim)